
export const elPasoRobao = {
  id: 1, // This will be auto-generated by Prisma
  image: '/images/paso_robao.jpg', // URL to an image or you can use a base64 string
  title: 'El Paso Robao',
  subtitle: 'A Historical Landmark in Mompox',
  description: 'El Paso Robao is a historic landmark in Mompox known for its rich cultural heritage and architectural beauty. It is an essential part of the town’s history and a popular site for visitors.',
  details: {
    yearBuilt: 1780,
    architect: 'Unknown',
    historicalSignificance: 'This building has served various purposes over the centuries, including as a government office and a meeting place for local leaders.',
    currentStatus: 'Preserved and open to the public',
  },
  frequentQuestions: {
    'What is the best time to visit?': 'The best time to visit is during the dry season from December to March.',
    'Are there guided tours available?': 'Yes, guided tours are available every day from 9 AM to 5 PM.',
    'Is there an entrance fee?': 'No, the entrance is free for all visitors.',
  },
};
