export const elPasoGrande = {
  id: 2, // This will be auto-generated by Prisma. 'seems to be giving an error if not provided when doing create.'
  image: '/images/paso_grande.jpg', // URL to an image or you can use a base64 string
  title: 'El Paso Grande',
  subtitle: 'A Majestic Landmark in Mompox',
  description: 'El Paso Grande is a majestic landmark in Mompox, celebrated for its grand architecture and historical importance. It stands as a testament to the town’s rich cultural legacy and attracts numerous visitors each year.',
  details: {
    yearBuilt: 1800,
    architect: 'Renowned Architect',
    historicalSignificance: 'El Paso Grande has been a central hub for cultural and social activities in Mompox, hosting numerous significant events over the years.',
    currentStatus: 'Well-maintained and open to the public',
  },
  frequentQuestions: {
    'What is the best time to visit?': 'The best time to visit is during the festive season from April to June.',
    'Are there guided tours available?': 'Yes, guided tours are available every day from 10 AM to 6 PM.',
    'Is there an entrance fee?': 'Yes, there is a nominal entrance fee of $5 for adults and $2 for children.',
  },
};