// Generated by ts-to-zod online: https://transform.tools/typescript-to-zod
import { z } from "zod";


const detailSchema = z.object({
  id: z.number(),
  key: z.string(),
  value: z.string(),
  objectId: z.number()
})

const frequentQuestionSchema = z.object({
  id: z.number(),
  question: z.string(),
  answer: z.string(),
  objectId: z.number()
})

export const objectSchema = z.object({
  id: z.number(),
  slug: z.string(),
  image: z.string().nullable(),
  title: z.string(),
  subtitle: z.string().nullable(),
  description: z.string(),
  createdAt: z.string().transform((str) => new Date(str)), // From prisma docs: 'Prisma Client returns all DateTime as native Date objects.'
  details: z.array(detailSchema).optional(),
  frequentQuestions: z.array(frequentQuestionSchema).optional()
})
