import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import '@smastrom/react-rating/style.css'
import { initMercadoPago } from '@mercadopago/sdk-react';

// Initialize MercadoPago
try {
  // initMercadoPago(process.env.PUBLIC_KEY_MERCADOPAGO ?? '');
  initMercadoPago('TEST-e0ee2946-9643-4f8a-8f25-0a642b018393', {locale: 'es-CO'})
  console.log("MercadoPago initialized successfully");
} catch (error) {
  console.error("Error initializing MercadoPago:", error);
}




const work_sans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={work_sans.className}>{children}
      </body>
    </html>
  );
}
